name: nucleus_one_dart_sdk
description: Ademero Nucleus One SDK for Dart
version: 0.0.0
homepage: https://www.ademero.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  get_it: ^5.0.6
  http: ^0.12.2
  js: ^0.6.2
  coverage: ^0.14.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.7