name: nucleus_one_dart_sdk
description: Ademero Nucleus One SDK for Dart
version: 0.0.0
homepage: https://www.ademero.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  built_value: ^8.0.4
  get_it: ^6.0.0
  http: ^0.13.0

dev_dependencies:
  build_runner: ^1.11.5
  built_value_generator: ^8.0.4
  coverage: ^1.0.2
  mockito: ^5.0.2
  pedantic: ^1.11.0
  remove_from_coverage: ^1.0.7
  test: ^1.16.8

dependency_overrides:
  # Temporary to address the following development dependency error
  #   Because no versions of remove_from_coverage match >1.0.7 <2.0.0 and remove_from_coverage 1.0.7 depends on args ^1.4.4, remove_from_coverage ^1.0.7 requires args ^1.4.4.
  #   And because coverage 1.0.2 depends on args ^2.0.0 and no versions of coverage match >1.0.2 <2.0.0, remove_from_coverage ^1.0
  # The remove_from_coverage package is only needed because the coverage package doesn't yet support ignoring generated (*.g.dart) files.
  args: ^2.0.0