name: nucleus_one_dart_sdk
description: Ademero Nucleus One SDK for Dart
version: 0.0.0
homepage: https://www.ademero.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  built_value: ^8.0.4
  get_it: ^6.0.0
  http: ^0.13.0

dev_dependencies:
  build_runner: ^1.11.5
  built_value_generator: ^8.0.4
  coverage: ^0.14.2
  mockito: ^4.1.4
  pedantic: ^1.9.0
  remove_from_coverage: ^1.0.7
  test: ^1.15.7