name: nucleus_one_dart_sdk
description: Ademero Nucleus One SDK for Dart
version: 0.0.0
homepage: https://www.ademero.com

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  file: ^6.1.2
  get_it: ^7.2.0
  http: ^0.13.4
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  collection: ^1.16.0

dev_dependencies:
  build_runner: ^2.3.3
  coverage: ^1.6.1
  mocktail: ^0.3.0
  pedantic: ^1.11.0   # Deprecated; needs to be migrated.  See pub.deb for details.
  remove_from_coverage: ^2.0.0
  test: ^1.22.1

# dependency_overrides: