name: nucleus_one_dart_sdk
description: Ademero Nucleus One SDK for Dart
version: 0.0.0
homepage: https://www.ademero.com

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  file: ^6.1.4
  get_it: ^7.6.0
  http: ^0.13.6
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  coverage: ^1.6.4
  lints: ^2.0.1
  mocktail: ^1.0.1
  remove_from_coverage: ^2.0.0
  test: ^1.24.3

# dependency_overrides: