import 'package:get_it/get_it.dart';

import '../api_model/document_subscription_for_client.dart' as api_mod;
import '../nucleus_one.dart';

// Originally generated by nucleus_one_utilities.
class DocumentSubscriptionForClient with NucleusOneAppDependent {
  DocumentSubscriptionForClient._({
    NucleusOneAppInternal? app,
    required this.subscribed,
    required this.notify,
    required this.createdOn,
    required this.documentID,
    required this.documentCreatedOn,
    required this.documentName,
    required this.documentPageCount,
    required this.documentFileSize,
    required this.documentClassificationID,
    required this.documentClassificationName,
    required this.documentPreviewMetadata,
    required this.documentIsSigned,
  }) {
    this.app = app ?? GetIt.instance.get<NucleusOneApp>() as NucleusOneAppInternal;
  }

  factory DocumentSubscriptionForClient.fromApiModel(
      api_mod.DocumentSubscriptionForClient apiModel) {
    return DocumentSubscriptionForClient._(
      subscribed: apiModel.subscribed!,
      notify: apiModel.notify!,
      createdOn: apiModel.createdOn!,
      documentID: apiModel.documentID!,
      documentCreatedOn: apiModel.documentCreatedOn!,
      documentName: apiModel.documentName!,
      documentPageCount: apiModel.documentPageCount!,
      documentFileSize: apiModel.documentFileSize!,
      documentClassificationID: apiModel.documentClassificationID!,
      documentClassificationName: apiModel.documentClassificationName!,
      documentPreviewMetadata:
          apiModel.documentPreviewMetadata!.map((x) => Map<String, String>.from(x)).toList(),
      documentIsSigned: apiModel.documentIsSigned!,
    );
  }

  bool subscribed;

  bool notify;

  String createdOn;

  String documentID;

  String documentCreatedOn;

  String documentName;

  int documentPageCount;

  int documentFileSize;

  String documentClassificationID;

  String documentClassificationName;

  List<Map<String, String>> documentPreviewMetadata;

  bool documentIsSigned;

  api_mod.DocumentSubscriptionForClient toApiModel() {
    return api_mod.DocumentSubscriptionForClient()
      ..subscribed = subscribed
      ..notify = notify
      ..createdOn = createdOn
      ..documentID = documentID
      ..documentCreatedOn = documentCreatedOn
      ..documentName = documentName
      ..documentPageCount = documentPageCount
      ..documentFileSize = documentFileSize
      ..documentClassificationID = documentClassificationID
      ..documentClassificationName = documentClassificationName
      ..documentPreviewMetadata = documentPreviewMetadata.toList()
      ..documentIsSigned = documentIsSigned;
  }
}
