import '../api_model/email_login_options.dart' as api_mod;
import '../common/get_it.dart';
import '../common/model.dart';
import '../nucleus_one.dart';

// Originally generated by nucleus_one_utilities
class EmailLoginOptions extends Entity with NucleusOneAppDependent {
  EmailLoginOptions._({
    NucleusOneApp? app,
    required this.userExists,
    required this.smsNumberLast2,
  }) {
    this.app = getEffectiveNucleusOneApp(app);
  }

  factory EmailLoginOptions.fromApiModel(
    api_mod.EmailLoginOptions apiModel, {
    NucleusOneApp? app,
  }) {
    return EmailLoginOptions._(
      app: app,
      userExists: apiModel.userExists!,
      smsNumberLast2: apiModel.smsNumberLast2!,
    );
  }

  bool userExists;

  String smsNumberLast2;

  @override
  api_mod.EmailLoginOptions toApiModel() {
    return api_mod.EmailLoginOptions()
      ..userExists = userExists
      ..smsNumberLast2 = smsNumberLast2;
  }
}
