import '../api_model/form_submission_field.dart' as api_mod;
import '../common/get_it.dart';
import '../common/model.dart';
import '../nucleus_one.dart';
import 'form_template_field.dart';

// Originally generated by nucleus_one_utilities.
class FormSubmissionField extends Entity with NucleusOneAppDependent, FormTemplateFieldMixin {
  FormSubmissionField._({
    NucleusOneApp? app,
    required this.formTemplateFieldID,
  }) {
    this.app = app ?? getIt.get<NucleusOneApp>();
  }

  factory FormSubmissionField.fromFormTemplateField(FormTemplateField field) {
    final fsf = FormSubmissionField._(
      formTemplateFieldID: null,
      app: field.app,
    );
    // Copy the field values from the FormTemplateField to the FormSubmissionField instance
    FormTemplateFieldMixin.fromApiModel(
      fsf,
      field.toApiModel(),
      app: field.app,
    );
    return fsf;
  }

  factory FormSubmissionField.fromApiModel(
    api_mod.FormSubmissionField apiModel, {
    NucleusOneApp? app,
  }) {
    final model = FormSubmissionField._(
      formTemplateFieldID: apiModel.formTemplateFieldID,
    );
    FormTemplateFieldMixin.fromApiModel(
      model,
      apiModel,
      app: app,
    );
    return model;
  }

  @override
  api_mod.FormSubmissionField toApiModel() {
    final apiModel = api_mod.FormSubmissionField()..formTemplateFieldID = formTemplateFieldID;
    super.formTemplateFieldMixinToApiModel(apiModel);
    return apiModel;
  }

  String? formTemplateFieldID;
}
