import '../api_model/organization.dart' as api_mod;
import '../common/get_it.dart';
import '../common/model.dart';
import '../nucleus_one.dart';

// Originally generated by nucleus_one_utilities.
class Organization extends Entity with NucleusOneAppDependent {
  Organization._({
    NucleusOneApp? app,
    required this.id,
    required this.createdOn,
    required this.bucketName,
    required this.name,
    required this.nameLower,
    required this.creatingUserID,
    required this.creatingUserName,
    required this.creatingUserEmail,
    required this.crmAccountId,
    required this.crmLeadId,
    required this.crmContactId,
    required this.crmDealId,
    required this.disabled,
    required this.isMarkedForPurge,
    required this.purgeMarkedOn,
    required this.purgeMarkedByUserID,
    required this.purgeMarkedByUserName,
    required this.purgeMarkedByUserEmail,
    required this.subscriptionRequired,
    required this.subscriptionFreeUsers,
    required this.subscriptionExpiration,
    required this.searchIndexRemovedForCostSavings,
    required this.searchIndexRestoredAtLeastOnce,
  }) {
    this.app = app ?? getIt.get<NucleusOneApp>();
  }

  factory Organization.fromApiModel(
    api_mod.Organization apiModel, {
    NucleusOneApp? app,
  }) {
    return Organization._(
      app: app,
      id: apiModel.id!,
      createdOn: apiModel.createdOn!,
      bucketName: apiModel.bucketName!,
      name: apiModel.name!,
      nameLower: apiModel.nameLower!,
      creatingUserID: apiModel.creatingUserID!,
      creatingUserName: apiModel.creatingUserName!,
      creatingUserEmail: apiModel.creatingUserEmail!,
      crmAccountId: apiModel.crmAccountId!,
      crmLeadId: apiModel.crmLeadId!,
      crmContactId: apiModel.crmContactId!,
      crmDealId: apiModel.crmDealId!,
      disabled: apiModel.disabled!,
      isMarkedForPurge: apiModel.isMarkedForPurge!,
      purgeMarkedOn: apiModel.purgeMarkedOn!,
      purgeMarkedByUserID: apiModel.purgeMarkedByUserID!,
      purgeMarkedByUserName: apiModel.purgeMarkedByUserName!,
      purgeMarkedByUserEmail: apiModel.purgeMarkedByUserEmail!,
      subscriptionRequired: apiModel.subscriptionRequired!,
      subscriptionFreeUsers: apiModel.subscriptionFreeUsers!,
      subscriptionExpiration: apiModel.subscriptionExpiration!,
      searchIndexRemovedForCostSavings: apiModel.searchIndexRemovedForCostSavings!,
      searchIndexRestoredAtLeastOnce: apiModel.searchIndexRestoredAtLeastOnce!,
    );
  }

  String id;

  String createdOn;

  String bucketName;

  String name;

  String nameLower;

  String creatingUserID;

  String creatingUserName;

  String creatingUserEmail;

  String crmAccountId;

  String crmLeadId;

  String crmContactId;

  String crmDealId;

  bool disabled;

  bool isMarkedForPurge;

  String purgeMarkedOn;

  String purgeMarkedByUserID;

  String purgeMarkedByUserName;

  String purgeMarkedByUserEmail;

  bool subscriptionRequired;

  int subscriptionFreeUsers;

  String subscriptionExpiration;

  bool searchIndexRemovedForCostSavings;

  bool searchIndexRestoredAtLeastOnce;

  @override
  api_mod.Organization toApiModel() {
    return api_mod.Organization()
      ..id = id
      ..createdOn = createdOn
      ..bucketName = bucketName
      ..name = name
      ..nameLower = nameLower
      ..creatingUserID = creatingUserID
      ..creatingUserName = creatingUserName
      ..creatingUserEmail = creatingUserEmail
      ..crmAccountId = crmAccountId
      ..crmLeadId = crmLeadId
      ..crmContactId = crmContactId
      ..crmDealId = crmDealId
      ..disabled = disabled
      ..isMarkedForPurge = isMarkedForPurge
      ..purgeMarkedOn = purgeMarkedOn
      ..purgeMarkedByUserID = purgeMarkedByUserID
      ..purgeMarkedByUserName = purgeMarkedByUserName
      ..purgeMarkedByUserEmail = purgeMarkedByUserEmail
      ..subscriptionRequired = subscriptionRequired
      ..subscriptionFreeUsers = subscriptionFreeUsers
      ..subscriptionExpiration = subscriptionExpiration
      ..searchIndexRemovedForCostSavings = searchIndexRemovedForCostSavings
      ..searchIndexRestoredAtLeastOnce = searchIndexRestoredAtLeastOnce;
  }
}
