import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';
import 'query_result.dart';

part 'classification.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class ClassificationCollection implements IQueryResultEntityCollection {
  ClassificationCollection();

  /// A necessary factory constructor for creating a new ClassificationCollection instance
  /// from a map. Pass the map to the generated [_$ClassificationCollectionFromJson()] constructor.
  /// The constructor is named after the source class, in this case, ClassificationCollection.
  factory ClassificationCollection.fromJson(Map<String, dynamic> json) =>
      _$ClassificationCollectionFromJson(json);

  @JsonKey(name: 'Classifications')
  List<Classification>? classifications;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$ClassificationCollectionToJson].
  Map<String, dynamic> toJson() => _$ClassificationCollectionToJson(this);
  // coverage:ignore-end
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class Classification extends Entity {
  Classification();

  /// A necessary factory constructor for creating a new Classification instance
  /// from a map. Pass the map to the generated [_$ClassificationFromJson()] constructor.
  /// The constructor is named after the source class, in this case, Classification.
  factory Classification.fromJson(Map<String, dynamic> json) => _$ClassificationFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'Name')
  String? name;

  @JsonKey(name: 'NameLower')
  String? nameLower;

  @JsonKey(name: 'IsActive')
  bool? isActive;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$ClassificationToJson].
  @override
  Map<String, dynamic> toJson() => _$ClassificationToJson(this);
  // coverage:ignore-end
}
