import 'package:json_annotation/json_annotation.dart';

import 'index_field.dart';
import 'document.dart';
import 'document_subscription.dart';
import 'classification_field.dart';

part 'document_package.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentPackage {
  DocumentPackage();

  /// A necessary factory constructor for creating a new DocumentPackage instance
  /// from a map. Pass the map to the generated [_$DocumentPackageFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentPackage.
  factory DocumentPackage.fromJson(Map<String, dynamic> json) => _$DocumentPackageFromJson(json);

  @JsonKey(name: 'Document')
  Document? document;

  @JsonKey(name: 'DocumentSubscription')
  DocumentSubscription? documentSubscription;

  @JsonKey(name: 'Approval')
  dynamic? approval;

  @JsonKey(name: 'ClassificationField')
  ClassificationField? classificationField;

  @JsonKey(name: 'IndexFields')
  List<IndexField>? indexFields;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentPackageToJson].
  Map<String, dynamic> toJson() => _$DocumentPackageToJson(this);
  // coverage:ignore-end
}
