import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';
import 'query_result.dart';

part 'document.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class Document extends Entity {
  Document();

  /// A necessary factory constructor for creating a new Document instance
  /// from a map. Pass the map to the generated [_$DocumentFromJson()] constructor.
  /// The constructor is named after the source class, in this case, Document.
  factory Document.fromJson(Map<String, dynamic> json) => _$DocumentFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'OrganizationID')
  String? organizationID;

  @JsonKey(name: 'ProjectID')
  String? projectID;

  @JsonKey(name: 'ProjectName')
  String? projectName;

  @JsonKey(name: 'ProjectAccessType')
  String? projectAccessType;

  @JsonKey(name: 'DocumentID')
  String? documentID;

  @JsonKey(name: 'DocumentFolderID')
  String? documentFolderID;

  @JsonKey(name: 'DocumentFolderPath')
  String? documentFolderPath;

  @JsonKey(name: 'AssignmentUserEmails')
  List<String>? assignmentUserEmails;

  @JsonKey(name: 'GroupID')
  String? groupID;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'CreatedByUserEmail')
  String? createdByUserEmail;

  @JsonKey(name: 'CreatedByUserName')
  String? createdByUserName;

  @JsonKey(name: 'ModifiedOn')
  String? modifiedOn;

  @JsonKey(name: 'ModifiedByUserEmail')
  String? modifiedByUserEmail;

  @JsonKey(name: 'ModifiedByUserName')
  String? modifiedByUserName;

  @JsonKey(name: 'PurgeDate')
  String? purgeDate;

  @JsonKey(name: 'Name')
  String? name;

  @JsonKey(name: 'Origin')
  String? origin;

  @JsonKey(name: 'PageCount')
  int? pageCount;

  @JsonKey(name: 'FileSize')
  int? fileSize;

  @JsonKey(name: 'ThumbnailUrl')
  String? thumbnailUrl;

  @JsonKey(name: 'IsSigned')
  bool? isSigned;

  @JsonKey(name: 'PreviewMetadata')
  List<Map<String, String>>? previewMetadata;

  @JsonKey(name: 'ApprovalID')
  String? approvalID;

  @JsonKey(name: 'ApprovalCreatedOn')
  String? approvalCreatedOn;

  @JsonKey(name: 'IsMarkedForPurge')
  bool? isMarkedForPurge;

  @JsonKey(name: 'HasSinglePageImages')
  bool? hasSinglePageImages;

  @JsonKey(name: 'SignatureSessionIsActive')
  bool? signatureSessionIsActive;

  @JsonKey(name: 'SignaturesCompletedOn')
  String? signaturesCompletedOn;

  @JsonKey(name: 'DocumentSubscriptionID')
  String? documentSubscriptionID;

  @JsonKey(name: 'DocumentSubscriptionCreatedOn')
  String? documentSubscriptionCreatedOn;

  @JsonKey(name: 'ProcessName')
  String? processName;

  @JsonKey(name: 'ProcessElementName')
  String? processElementName;

  @JsonKey(name: 'Revision')
  int? revision;

  @JsonKey(name: 'PaperSize')
  String? paperSize;

  @JsonKey(name: 'PaperOrientation')
  String? paperOrientation;

  @JsonKey(name: 'PaperMarginLeft')
  int? paperMarginLeft;

  @JsonKey(name: 'PaperMarginRight')
  int? paperMarginRight;

  @JsonKey(name: 'PaperMarginTop')
  int? paperMarginTop;

  @JsonKey(name: 'PaperMarginBottom')
  int? paperMarginBottom;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentToJson].
  @override
  Map<String, dynamic> toJson() => _$DocumentToJson(this);
  // coverage:ignore-end
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentCollection implements IQueryResultEntityCollection {
  DocumentCollection();

  /// A necessary factory constructor for creating a new DocumentCollection instance
  /// from a map. Pass the map to the generated [_$DocumentCollectionFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentCollection.
  factory DocumentCollection.fromJson(Map<String, dynamic> json) =>
      _$DocumentCollectionFromJson(json);

  @JsonKey(name: 'Documents')
  List<Document>? documents;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentCollectionToJson].
  Map<String, dynamic> toJson() => _$DocumentCollectionToJson(this);
  // coverage:ignore-end
}
