import 'package:json_annotation/json_annotation.dart';

part 'document_signature_form.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentSignatureForm {
  DocumentSignatureForm();

  /// A necessary factory constructor for creating a new DocumentSignatureForm instance
  /// from a map. Pass the map to the generated [_$DocumentSignatureFormFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentSignatureForm.
  factory DocumentSignatureForm.fromJson(Map<String, dynamic> json) =>
      _$DocumentSignatureFormFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'SignatureFormTemplateID')
  String? signatureFormTemplateID;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'TenantID')
  String? tenantID;

  @JsonKey(name: 'DocumentID')
  String? documentID;

  @JsonKey(name: 'DocumentClassificationID')
  String? documentClassificationID;

  @JsonKey(name: 'DocumentClassificationName')
  String? documentClassificationName;

  @JsonKey(name: 'DocumentClassificationNameLower')
  String? documentClassificationNameLower;

  @JsonKey(name: 'DocumentName')
  String? documentName;

  @JsonKey(name: 'DocumentNameLower')
  String? documentNameLower;

  @JsonKey(name: 'HasFormFields')
  bool? hasFormFields;

  @JsonKey(name: 'TotalFormFields')
  int? totalFormFields;

  @JsonKey(name: 'LastViewedPageIndex')
  int? lastViewedPageIndex;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentSignatureFormToJson].
  Map<String, dynamic> toJson() => _$DocumentSignatureFormToJson(this);
  // coverage:ignore-end
}
