// ignore_for_file: unused_import

import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';

import 'document_content_package.dart';
import 'document_signature_session_form_field_package.dart';
import 'document_signature_session_recipient_form_field.dart';
import 'document_signature_session_signing_recipient.dart';

part 'document_signature_session_signing_recipient_package.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentSignatureSessionSigningRecipientPackage extends Entity {
  DocumentSignatureSessionSigningRecipientPackage();

  /// A necessary factory constructor for creating a new DocumentSignatureSessionSigningRecipientPackage instance
  /// from a map. Pass the map to the generated [_$DocumentSignatureSessionSigningRecipientPackageFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentSignatureSessionSigningRecipientPackage.
  factory DocumentSignatureSessionSigningRecipientPackage.fromJson(Map<String, dynamic> json) =>
      _$DocumentSignatureSessionSigningRecipientPackageFromJson(json);

  @JsonKey(name: 'RequireAccessCode')
  bool? requireAccessCode;

  @JsonKey(name: 'SigningRecipient')
  DocumentSignatureSessionSigningRecipient? signingRecipient;

  @JsonKey(name: 'FormFieldPackage')
  DocumentSignatureSessionFormFieldPackage? formFieldPackage;

  @JsonKey(name: 'ServerDate')
  String? serverDate;

  @JsonKey(name: 'ContentPackage')
  DocumentContentPackage? contentPackage;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentSignatureSessionSigningRecipientPackageToJson].
  @override
  Map<String, dynamic> toJson() => _$DocumentSignatureSessionSigningRecipientPackageToJson(this);
  // coverage:ignore-end
}
