import 'package:json_annotation/json_annotation.dart';

import 'document_event.dart';
import 'query_result.dart';

part 'document_comment.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentCommentCollection implements IQueryResultEntityCollection {
  DocumentCommentCollection();

  /// A necessary factory constructor for creating a new DocumentCommentCollection instance
  /// from a map. Pass the map to the generated [_$DocumentCommentsFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentCommentCollection.
  factory DocumentCommentCollection.fromJson(Map<String, dynamic> json) =>
      _$DocumentCommentCollectionFromJson(json);

  @JsonKey(name: 'DocumentEvents')
  List<DocumentEvent>? documentEvents;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentCommentsToJson].
  Map<String, dynamic> toJson() => _$DocumentCommentCollectionToJson(this);
  // coverage:ignore-end
}
