import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';
import 'document_signature_session_recipient_form_field.dart';

part 'document_signature_session_form_field_package.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentSignatureSessionFormFieldPackage extends Entity {
  DocumentSignatureSessionFormFieldPackage();

  /// A necessary factory constructor for creating a new DocumentSignatureSessionFormFieldPackage instance
  /// from a map. Pass the map to the generated [_$DocumentSignatureSessionFormFieldPackageFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentSignatureSessionFormFieldPackage.
  factory DocumentSignatureSessionFormFieldPackage.fromJson(Map<String, dynamic> json) =>
      _$DocumentSignatureSessionFormFieldPackageFromJson(json);

  @JsonKey(name: 'FormDesignType')
  String? formDesignType;

  @JsonKey(name: 'QuickDesignPlaceInitials')
  bool? quickDesignPlaceInitials;

  @JsonKey(name: 'QuickDesignPlaceFullName')
  bool? quickDesignPlaceFullName;

  @JsonKey(name: 'QuickDesignPlaceEmail')
  bool? quickDesignPlaceEmail;

  @JsonKey(name: 'QuickDesignPlaceTitle')
  bool? quickDesignPlaceTitle;

  @JsonKey(name: 'FormFields')
  List<DocumentSignatureSessionRecipientFormField>? formFields;

  @JsonKey(name: 'CompletedFormFields')
  List<DocumentSignatureSessionRecipientFormField>? completedFormFields;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentSignatureSessionFormFieldPackageToJson].
  @override
  Map<String, dynamic> toJson() => _$DocumentSignatureSessionFormFieldPackageToJson(this);
  // coverage:ignore-end
}
