import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';

part 'document_signature_session.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentSignatureSession extends Entity {
  DocumentSignatureSession();

  /// A necessary factory constructor for creating a new DocumentSignatureSession instance
  /// from a map. Pass the map to the generated [_$DocumentSignatureSessionFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentSignatureSession.
  factory DocumentSignatureSession.fromJson(Map<String, dynamic> json) =>
      _$DocumentSignatureSessionFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'ModifiedOn')
  String? modifiedOn;

  @JsonKey(name: 'CreatedByUserID')
  String? createdByUserID;

  @JsonKey(name: 'CreatedByUserEmail')
  String? createdByUserEmail;

  @JsonKey(name: 'CreatedByUserName')
  String? createdByUserName;

  @JsonKey(name: 'LastModifiedByUserID')
  String? lastModifiedByUserID;

  @JsonKey(name: 'LastModifiedByUserEmail')
  String? lastModifiedByUserEmail;

  @JsonKey(name: 'LastModifiedByUserName')
  String? lastModifiedByUserName;

  @JsonKey(name: 'DocumentID')
  String? documentID;

  @JsonKey(name: 'DocumentRevisionID')
  String? documentRevisionID;

  @JsonKey(name: 'IsActive')
  bool? isActive;

  @JsonKey(name: 'IsComplete')
  bool? isComplete;

  @JsonKey(name: 'WasStopped')
  bool? wasStopped;

  @JsonKey(name: 'CompletedOn')
  String? completedOn;

  @JsonKey(name: 'IsRendered')
  bool? isRendered;

  @JsonKey(name: 'RenderedOn')
  String? renderedOn;

  @JsonKey(name: 'FormDesignType')
  String? formDesignType;

  @JsonKey(name: 'UseAccessCode')
  bool? useAccessCode;

  @JsonKey(name: 'AccessCode')
  String? accessCode;

  @JsonKey(name: 'UseCustomSubjectAndBody')
  bool? useCustomSubjectAndBody;

  @JsonKey(name: 'CustomSubject')
  String? customSubject;

  @JsonKey(name: 'CustomBody')
  String? customBody;

  @JsonKey(name: 'QuickDesignPlaceInitials')
  bool? quickDesignPlaceInitials;

  @JsonKey(name: 'QuickDesignPlaceFullName')
  bool? quickDesignPlaceFullName;

  @JsonKey(name: 'QuickDesignPlaceEmail')
  bool? quickDesignPlaceEmail;

  @JsonKey(name: 'QuickDesignPlaceTitle')
  bool? quickDesignPlaceTitle;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentSignatureSessionToJson].
  @override
  Map<String, dynamic> toJson() => _$DocumentSignatureSessionToJson(this);
  // coverage:ignore-end
}
