import 'package:json_annotation/json_annotation.dart';

part 'document_upload.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentUpload {
  DocumentUpload();

  /// A necessary factory constructor for creating a new DocumentUpload instance
  /// from a map. Pass the map to the generated [_$DocumentUploadFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentUpload.
  factory DocumentUpload.fromJson(Map<String, dynamic> json) => _$DocumentUploadFromJson(json);

  @JsonKey(name: 'SignedUrl')
  String? signedUrl;

  @JsonKey(name: 'ObjectName')
  String? objectName;

  @JsonKey(name: 'UniqueId')
  String? uniqueId;

  @JsonKey(name: 'OriginalFilename')
  String? originalFilename;

  @JsonKey(name: 'OriginalFileSize')
  int? originalFileSize;

  @JsonKey(name: 'ClassificationID')
  String? classificationID;

  @JsonKey(name: 'FieldIDsAndValues')
  Map<String, List<String>>? fieldIDsAndValues;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentUploadToJson].
  Map<String, dynamic> toJson() => _$DocumentUploadToJson(this);
  // coverage:ignore-end
}
