import 'package:json_annotation/json_annotation.dart';

part 'document_signature_form_field.g.dart';

// Originally generated by nucleus_one_utilities.
class DocumentSignatureFormFieldCollection {
  DocumentSignatureFormFieldCollection() : items = [];

  /// This JSON structure has an array at its root, which is not currently implicitly supported by json_serializable.
  /// https://github.com/google/json_serializable.dart/issues/648
  factory DocumentSignatureFormFieldCollection.fromJson(List<dynamic> json) {
    return DocumentSignatureFormFieldCollection()..items = json.map((m) => DocumentSignatureFormField.fromJson(m)).toList();
  }

  List<DocumentSignatureFormField> items;
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentSignatureFormField {
  DocumentSignatureFormField();

  /// A necessary factory constructor for creating a new DocumentSignatureFormField instance
  /// from a map. Pass the map to the generated [_$DocumentSignatureFormFieldFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentSignatureFormField.
  factory DocumentSignatureFormField.fromJson(Map<String, dynamic> json) =>
      _$DocumentSignatureFormFieldFromJson(json);

  @JsonKey(name: 'Type')
  String? type;

  @JsonKey(name: 'Label')
  String? label;

  @JsonKey(name: 'WidthPercent')
  double? widthPercent;

  @JsonKey(name: 'SortRank')
  int? sortRank;

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'DocumentSignatureSessionRecipientID')
  String? documentSignatureSessionRecipientID;

  @JsonKey(name: 'X')
  double? x;

  @JsonKey(name: 'Y')
  double? y;

  @JsonKey(name: 'PageIndex')
  int? pageIndex;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentSignatureFormFieldToJson].
  Map<String, dynamic> toJson() => _$DocumentSignatureFormFieldToJson(this);
  // coverage:ignore-end
}
