import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';

part 'document_subscription_for_client.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentSubscriptionForClient extends Entity {
  DocumentSubscriptionForClient();

  /// A necessary factory constructor for creating a new DocumentSubscriptionForClient instance
  /// from a map. Pass the map to the generated [_$DocumentSubscriptionForClientFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentSubscriptionForClient.
  factory DocumentSubscriptionForClient.fromJson(Map<String, dynamic> json) =>
      _$DocumentSubscriptionForClientFromJson(json);

  @JsonKey(name: 'Subscribed')
  bool? subscribed;

  @JsonKey(name: 'Notify')
  bool? notify;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'DocumentID')
  String? documentID;

  @JsonKey(name: 'DocumentCreatedOn')
  String? documentCreatedOn;

  @JsonKey(name: 'DocumentName')
  String? documentName;

  @JsonKey(name: 'DocumentPageCount')
  int? documentPageCount;

  @JsonKey(name: 'DocumentFileSize')
  int? documentFileSize;

  @JsonKey(name: 'DocumentClassificationID')
  String? documentClassificationID;

  @JsonKey(name: 'DocumentClassificationName')
  String? documentClassificationName;

  @JsonKey(name: 'DocumentPreviewMetadata')
  List<Map<String, String>>? documentPreviewMetadata;

  @JsonKey(name: 'DocumentIsSigned')
  bool? documentIsSigned;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentSubscriptionForClientToJson].
  @override
  Map<String, dynamic> toJson() => _$DocumentSubscriptionForClientToJson(this);
  // coverage:ignore-end
}
