import 'package:json_annotation/json_annotation.dart';

import 'document_event.dart';

part 'document_comments.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentComments {
  DocumentComments();

  /// A necessary factory constructor for creating a new DocumentComments instance
  /// from a map. Pass the map to the generated [_$DocumentCommentsFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentComments.
  factory DocumentComments.fromJson(Map<String, dynamic> json) => _$DocumentCommentsFromJson(json);

  @JsonKey(name: 'DocumentEvents')
  List<DocumentEvent>? documentEvents;

  @JsonKey(name: 'Cursor')
  String? cursor;

  @JsonKey(name: 'ReverseCursor')
  String? reverseCursor;

  @JsonKey(name: 'PageSize')
  int? pageSize;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentCommentsToJson].
  Map<String, dynamic> toJson() => _$DocumentCommentsToJson(this);
  // coverage:ignore-end
}
