import 'package:json_annotation/json_annotation.dart';

import '../common/api_model.dart';
import 'document_signature_session.dart';
import 'document_signature_session_recipient.dart';

part 'document_signature_session_package.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentSignatureSessionPackage extends Entity {
  DocumentSignatureSessionPackage();

  /// A necessary factory constructor for creating a new DocumentSignatureSessionPackage instance
  /// from a map. Pass the map to the generated [_$DocumentSignatureSessionPackageFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentSignatureSessionPackage.
  factory DocumentSignatureSessionPackage.fromJson(Map<String, dynamic> json) =>
      _$DocumentSignatureSessionPackageFromJson(json);

  @JsonKey(name: 'Session')
  DocumentSignatureSession? session;

  @JsonKey(name: 'Recipients')
  List<DocumentSignatureSessionRecipient>? recipients;

  @JsonKey(name: 'BeginSession')
  bool? beginSession;

  @JsonKey(name: 'ResetSession')
  bool? resetSession;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentSignatureSessionPackageToJson].
  @override
  Map<String, dynamic> toJson() => _$DocumentSignatureSessionPackageToJson(this);
  // coverage:ignore-end
}

// Originally generated by nucleus_one_utilities.
class DocumentSignatureSessionPackageCollection
    extends EntityCollection<DocumentSignatureSessionPackage> {
  DocumentSignatureSessionPackageCollection() : super();

  factory DocumentSignatureSessionPackageCollection.fromJson(List<Map<String, dynamic>> json) {
    return EntityCollection.fromJsonArray(
      json: json,
      instance: DocumentSignatureSessionPackageCollection(),
      entityFromJsonCallback: (x) => DocumentSignatureSessionPackage.fromJson(x),
    );
  }
}
