import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';
import 'query_result.dart';

part 'document_event.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentEvent extends Entity {
  DocumentEvent();

  /// A necessary factory constructor for creating a new DocumentEvent instance
  /// from a map. Pass the map to the generated [_$DocumentEventFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentEvent.
  factory DocumentEvent.fromJson(Map<String, dynamic> json) => _$DocumentEventFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'DocumentID')
  String? documentID;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'CreatedByUserID')
  String? createdByUserID;

  @JsonKey(name: 'CreatedByUserName')
  String? createdByUserName;

  @JsonKey(name: 'CreatedByUserEmail')
  String? createdByUserEmail;

  @JsonKey(name: 'Type')
  String? type;

  @JsonKey(name: 'DetailJson')
  String? detailJson;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentEventToJson].
  @override
  Map<String, dynamic> toJson() => _$DocumentEventToJson(this);
  // coverage:ignore-end
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentEventCollection implements IQueryResultEntityCollection {
  DocumentEventCollection();

  /// A necessary factory constructor for creating a new DocumentEventCollection instance
  /// from a map. Pass the map to the generated [_$DocumentEventCollectionFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentEventCollection.
  factory DocumentEventCollection.fromJson(Map<String, dynamic> json) =>
      _$DocumentEventCollectionFromJson(json);

  @JsonKey(name: 'DocumentEvents')
  List<DocumentEvent>? documentEvents;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentEventCollectionToJson].
  Map<String, dynamic> toJson() => _$DocumentEventCollectionToJson(this);
  // coverage:ignore-end
}
