import 'package:json_annotation/json_annotation.dart';

part 'document_content_package.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentContentPackage {
  DocumentContentPackage();

  /// A necessary factory constructor for creating a new DocumentContentPackage instance
  /// from a map. Pass the map to the generated [_$DocumentContentPackageFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentContentPackage.
  factory DocumentContentPackage.fromJson(Map<String, dynamic> json) =>
      _$DocumentContentPackageFromJson(json);

  @JsonKey(name: 'Url')
  String? url;

  @JsonKey(name: 'ContentType')
  String? contentType;

  @JsonKey(name: 'Name')
  String? name;

  @JsonKey(name: 'PageIndex')
  int? pageIndex;

  @JsonKey(name: 'PageCount')
  int? pageCount;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentContentPackageToJson].
  Map<String, dynamic> toJson() => _$DocumentContentPackageToJson(this);
  // coverage:ignore-end
}
