import 'package:json_annotation/json_annotation.dart';
import 'package:nucleus_one_dart_sdk/src/common/model.dart';

import 'document_event.dart';

part 'document_events.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class DocumentEvents implements IApiModelPagingCursor2 {
  DocumentEvents();

  /// A necessary factory constructor for creating a new DocumentEvents instance
  /// from a map. Pass the map to the generated [_$DocumentEventsFromJson()] constructor.
  /// The constructor is named after the source class, in this case, DocumentEvents.
  factory DocumentEvents.fromJson(Map<String, dynamic> json) => _$DocumentEventsFromJson(json);

  @JsonKey(name: 'DocumentEvents')
  List<DocumentEvent>? documentEvents;

  @override
  @JsonKey(name: 'Cursor')
  String? cursor;

  @override
  @JsonKey(name: 'ReverseCursor')
  String? reverseCursor;

  @override
  @JsonKey(name: 'PageSize')
  int? pageSize;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$DocumentEventsToJson].
  Map<String, dynamic> toJson() => _$DocumentEventsToJson(this);
  // coverage:ignore-end
}
