import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';

part 'field_list_item.g.dart';

// Originally generated by nucleus_one_utilities.
class FieldListItemCollection extends EntityCollection<FieldListItem> {
  FieldListItemCollection() : super();

  factory FieldListItemCollection.fromJson(List<dynamic> json) {
    return EntityCollection.fromJson(
      json: json,
      instance: FieldListItemCollection(),
      entityFromJsonCallback: (x) => FieldListItem.fromJson(x),
    );
  }
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class FieldListItem extends Entity {
  FieldListItem();

  /// A necessary factory constructor for creating a new FieldListItem instance
  /// from a map. Pass the map to the generated [_$FieldListItemFromJson()] constructor.
  /// The constructor is named after the source class, in this case, FieldListItem.
  factory FieldListItem.fromJson(Map<String, dynamic> json) => _$FieldListItemFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'ParentValue')
  String? parentValue;

  @JsonKey(name: 'Value')
  String? value;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$FieldListItemToJson].
  @override
  Map<String, dynamic> toJson() => _$FieldListItemToJson(this);
  // coverage:ignore-end
}
