import 'package:json_annotation/json_annotation.dart';

import '../common/api_model.dart';
import 'query_result.dart';

part 'form_template.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class FormTemplate extends Entity {
  FormTemplate();

  /// A necessary factory constructor for creating a new FormTemplate instance
  /// from a map. Pass the map to the generated [_$FormTemplateFromJson()] constructor.
  /// The constructor is named after the source class, in this case, FormTemplate.
  factory FormTemplate.fromJson(Map<String, dynamic> json) => _$FormTemplateFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'TenantID')
  String? tenantID;

  @JsonKey(name: 'UniqueID')
  String? uniqueID;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'Name')
  String? name;

  @JsonKey(name: 'NameLower')
  String? nameLower;

  @JsonKey(name: 'PageCount')
  int? pageCount;

  @JsonKey(name: 'IsPublic')
  bool? isPublic;

  @JsonKey(name: 'ClassificationID')
  String? classificationID;

  @JsonKey(name: 'ClassificationName')
  String? classificationName;

  @JsonKey(name: 'ClassificationNameLower')
  String? classificationNameLower;

  @JsonKey(name: 'Aspect')
  double? aspect;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$FormTemplateToJson].
  @override
  Map<String, dynamic> toJson() => _$FormTemplateToJson(this);
  // coverage:ignore-end
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class FormTemplateCollection implements IQueryResultEntityCollection {
  FormTemplateCollection();

  /// A necessary factory constructor for creating a new FormTemplateCollection instance
  /// from a map. Pass the map to the generated [_$FormTemplateCollectionFromJson()] constructor.
  /// The constructor is named after the source class, in this case, FormTemplateCollection.
  factory FormTemplateCollection.fromJson(Map<String, dynamic> json) =>
      _$FormTemplateCollectionFromJson(json);

  @JsonKey(name: 'FormTemplates')
  List<FormTemplate>? formTemplates;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$FormTemplateCollectionToJson].
  Map<String, dynamic> toJson() => _$FormTemplateCollectionToJson(this);
  // coverage:ignore-end
}
