import 'package:json_annotation/json_annotation.dart';

import '../common/api_model.dart';
import 'field.dart';
import 'form_template_field.dart';

part 'form_submission_field.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class FormSubmissionField extends Entity with FormTemplateFieldMixin {
  FormSubmissionField();

  /// A necessary factory constructor for creating a new FormSubmissionField instance
  /// from a map. Pass the map to the generated [_$FormSubmissionFieldFromJson()] constructor.
  /// The constructor is named after the source class, in this case, FormSubmissionField.
  factory FormSubmissionField.fromJson(Map<String, dynamic> json) =>
      _$FormSubmissionFieldFromJson(json);

  @JsonKey(name: 'FormTemplateFieldID')
  String? formTemplateFieldID;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$FormSubmissionFieldToJson].
  @override
  Map<String, dynamic> toJson() => _$FormSubmissionFieldToJson(this);
  // coverage:ignore-end
}
