import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';

part 'organization.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class Organization extends Entity {
  Organization();

  /// A necessary factory constructor for creating a new Organization instance
  /// from a map. Pass the map to the generated [_$OrganizationFromJson()] constructor.
  /// The constructor is named after the source class, in this case, Organization.
  factory Organization.fromJson(Map<String, dynamic> json) => _$OrganizationFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'BucketName')
  String? bucketName;

  @JsonKey(name: 'Name')
  String? name;

  @JsonKey(name: 'NameLower')
  String? nameLower;

  @JsonKey(name: 'CreatingUserID')
  String? creatingUserID;

  @JsonKey(name: 'CreatingUserName')
  String? creatingUserName;

  @JsonKey(name: 'CreatingUserEmail')
  String? creatingUserEmail;

  @JsonKey(name: 'CrmAccountId')
  String? crmAccountId;

  @JsonKey(name: 'CrmLeadId')
  String? crmLeadId;

  @JsonKey(name: 'CrmContactId')
  String? crmContactId;

  @JsonKey(name: 'CrmDealId')
  String? crmDealId;

  @JsonKey(name: 'Disabled')
  bool? disabled;

  @JsonKey(name: 'IsMarkedForPurge')
  bool? isMarkedForPurge;

  @JsonKey(name: 'PurgeMarkedOn')
  String? purgeMarkedOn;

  @JsonKey(name: 'PurgeMarkedByUserID')
  String? purgeMarkedByUserID;

  @JsonKey(name: 'PurgeMarkedByUserName')
  String? purgeMarkedByUserName;

  @JsonKey(name: 'PurgeMarkedByUserEmail')
  String? purgeMarkedByUserEmail;

  @JsonKey(name: 'SubscriptionRequired')
  bool? subscriptionRequired;

  @JsonKey(name: 'SubscriptionFreeUsers')
  int? subscriptionFreeUsers;

  @JsonKey(name: 'SubscriptionExpiration')
  String? subscriptionExpiration;

  @JsonKey(name: 'SearchIndexRemovedForCostSavings')
  bool? searchIndexRemovedForCostSavings;

  @JsonKey(name: 'SearchIndexRestoredAtLeastOnce')
  bool? searchIndexRestoredAtLeastOnce;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$OrganizationToJson].
  @override
  Map<String, dynamic> toJson() => _$OrganizationToJson(this);
  // coverage:ignore-end
}
