import 'package:json_annotation/json_annotation.dart';

import '../common/api_model.dart';

part 'organization_assignment_type.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class OrganizationAssignmentType extends Entity {
  OrganizationAssignmentType();

  /// A necessary factory constructor for creating a new OrganizationAssignmentType instance
  /// from a map. Pass the map to the generated [_$OrganizationAssignmentTypeFromJson()] constructor.
  /// The constructor is named after the source class, in this case, OrganizationAssignmentType.
  factory OrganizationAssignmentType.fromJson(Map<String, dynamic> json) => _$OrganizationAssignmentTypeFromJson(json);

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$OrganizationAssignmentTypeToJson].
  @override
  Map<String, dynamic> toJson() => _$OrganizationAssignmentTypeToJson(this);
  // coverage:ignore-end
}
