import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';
import 'query_result.dart';

part 'organization_for_client.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class OrganizationForClient extends Entity {
  OrganizationForClient();

  /// A necessary factory constructor for creating a new OrganizationForClient instance
  /// from a map. Pass the map to the generated [_$OrganizationForClientFromJson()] constructor.
  /// The constructor is named after the source class, in this case, OrganizationForClient.
  factory OrganizationForClient.fromJson(Map<String, dynamic> json) =>
      _$OrganizationForClientFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'Name')
  String? name;

  @JsonKey(name: 'CreatedByUserID')
  String? createdByUserID;

  @JsonKey(name: 'CreatedByUserName')
  String? createdByUserName;

  @JsonKey(name: 'CreatedByUserEmail')
  String? createdByUserEmail;

  @JsonKey(name: 'SubscriptionRequired')
  bool? subscriptionRequired;

  @JsonKey(name: 'SubscriptionFreeUsers')
  int? subscriptionFreeUsers;

  @JsonKey(name: 'SubscriptionExpiration')
  String? subscriptionExpiration;

  @JsonKey(name: 'UniqueNonReadOnlyOrganizationMembers')
  int? uniqueNonReadOnlyOrganizationMembers;

  @JsonKey(name: 'UniqueReadOnlyOrganizationMembers')
  int? uniqueReadOnlyOrganizationMembers;

  @JsonKey(name: 'UniqueFreeOrganizationMembers')
  int? uniqueFreeOrganizationMembers;

  @JsonKey(name: 'UniqueBillableOrganizationMembers')
  int? uniqueBillableOrganizationMembers;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$OrganizationForClientToJson].
  @override
  Map<String, dynamic> toJson() => _$OrganizationForClientToJson(this);
  // coverage:ignore-end
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class OrganizationForClientCollection implements IQueryResultEntityCollection {
  OrganizationForClientCollection();

  /// A necessary factory constructor for creating a new FieldCollection instance
  /// from a map. Pass the map to the generated [_$OrganizationForClientCollectionFromJson()] constructor.
  /// The constructor is named after the source class, in this case, FieldCollection.
  factory OrganizationForClientCollection.fromJson(Map<String, dynamic> json) =>
      _$OrganizationForClientCollectionFromJson(json);

  /// This JSON structure has an array at its root, which is not currently implicitly supported by json_serializable.
  /// https://github.com/google/json_serializable.dart/issues/648
  factory OrganizationForClientCollection.fromJsonArray(List<dynamic> json) {
    return OrganizationForClientCollection()
      ..organizations = json.map((m) => OrganizationForClient.fromJson(m)).toList();
  }

  @JsonKey(name: 'Organizations')
  List<OrganizationForClient>? organizations;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$OrganizationForClientCollectionToJson].
  Map<String, dynamic> toJson() => _$OrganizationForClientCollectionToJson(this);
  // coverage:ignore-end
}
