import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';

part 'organization_permissions.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class OrganizationPermissions extends Entity {
  OrganizationPermissions();

  /// A necessary factory constructor for creating a new OrganizationPermissions instance
  /// from a map. Pass the map to the generated [_$OrganizationPermissionsFromJson()] constructor.
  /// The constructor is named after the source class, in this case, OrganizationPermissions.
  factory OrganizationPermissions.fromJson(Map<String, dynamic> json) =>
      _$OrganizationPermissionsFromJson(json);

  @JsonKey(name: 'OrganizationID')
  String? organizationID;

  @JsonKey(name: 'OrganizationName')
  String? organizationName;

  @JsonKey(name: 'UserID')
  String? userID;

  @JsonKey(name: 'UserName')
  String? userName;

  @JsonKey(name: 'UserEmail')
  String? userEmail;

  @JsonKey(name: 'IsAdmin')
  bool? isAdmin;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$OrganizationPermissionsToJson].
  @override
  Map<String, dynamic> toJson() => _$OrganizationPermissionsToJson(this);
  // coverage:ignore-end
}
