import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';
import 'organization.dart';
import 'organization_member.dart';
import 'query_result.dart';

part 'organization_membership_package.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class OrganizationMembershipPackage extends Entity {
  OrganizationMembershipPackage();

  /// A necessary factory constructor for creating a new OrganizationMembershipPackage instance
  /// from a map. Pass the map to the generated [_$OrganizationMembershipPackageFromJson()] constructor.
  /// The constructor is named after the source class, in this case, OrganizationMembershipPackage.
  factory OrganizationMembershipPackage.fromJson(Map<String, dynamic> json) =>
      _$OrganizationMembershipPackageFromJson(json);

  @JsonKey(name: 'Organization')
  Organization? organization;

  @JsonKey(name: 'OrganizationMember')
  OrganizationMember? organizationMember;

  @JsonKey(name: 'UserID')
  String? userID;

  @JsonKey(name: 'IsAdmin')
  bool? isAdmin;

  @JsonKey(name: 'IsExpiringSoon')
  bool? isExpiringSoon;

  @JsonKey(name: 'Expiration')
  String? expiration;

  @JsonKey(name: 'FreeUsers')
  int? freeUsers;

  @JsonKey(name: 'IsExpired')
  bool? isExpired;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$OrganizationMembershipPackageToJson].
  @override
  Map<String, dynamic> toJson() => _$OrganizationMembershipPackageToJson(this);
  // coverage:ignore-end
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class OrganizationMembershipPackageCollection implements IQueryResultEntityCollection {
  OrganizationMembershipPackageCollection();

  /// A necessary factory constructor for creating a new OrganizationMembershipPackageCollection instance
  /// from a map. Pass the map to the generated [_$OrganizationMembershipPackageCollectionFromJson()] constructor.
  /// The constructor is named after the source class, in this case, OrganizationMembershipPackageCollection.
  factory OrganizationMembershipPackageCollection.fromJson(Map<String, dynamic> json) =>
      _$OrganizationMembershipPackageCollectionFromJson(json);

  @JsonKey(name: 'OrganizationMembershipPackages')
  List<OrganizationMembershipPackage>? membershipPackages;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$OrganizationMembershipPackageCollectionToJson].
  Map<String, dynamic> toJson() => _$OrganizationMembershipPackageCollectionToJson(this);
  // coverage:ignore-end
}
