import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';

part 'preview_metadata_item.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class PreviewMetadataItem extends Entity {
  PreviewMetadataItem();

  /// A necessary factory constructor for creating a new PreviewMetadataItem instance
  /// from a map. Pass the map to the generated [_$PreviewMetadataItemFromJson()] constructor.
  /// The constructor is named after the source class, in this case, PreviewMetadataItem.
  factory PreviewMetadataItem.fromJson(Map<String, dynamic> json) =>
      _$PreviewMetadataItemFromJson(json);

  @JsonKey(name: '0')
  String? item0;

  @JsonKey(name: '1')
  String? item1;

  @JsonKey(name: '2')
  String? item2;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$PreviewMetadataItemToJson].
  @override
  Map<String, dynamic> toJson() => _$PreviewMetadataItemToJson(this);
  // coverage:ignore-end
}
