import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';

part 'signature_form_template.g.dart';

// Originally generated by nucleus_one_utilities.
class SignatureFormTemplateCollection extends EntityCollection<SignatureFormTemplate> {
  SignatureFormTemplateCollection() : super();

  factory SignatureFormTemplateCollection.fromJson(List<dynamic> json) {
    return EntityCollection.fromJson(
      json: json,
      instance: SignatureFormTemplateCollection(),
      entityFromJsonCallback: (x) => SignatureFormTemplate.fromJson(x),
    );
  }
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class SignatureFormTemplate extends Entity {
  SignatureFormTemplate();

  /// A necessary factory constructor for creating a new SignatureFormTemplate instance
  /// from a map. Pass the map to the generated [_$SignatureFormTemplateFromJson()] constructor.
  /// The constructor is named after the source class, in this case, SignatureFormTemplate.
  factory SignatureFormTemplate.fromJson(Map<String, dynamic> json) =>
      _$SignatureFormTemplateFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'Name')
  String? name;

  @JsonKey(name: 'NameLower')
  String? nameLower;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$SignatureFormTemplateToJson].
  @override
  Map<String, dynamic> toJson() => _$SignatureFormTemplateToJson(this);
  // coverage:ignore-end
}

// Originally generated by nucleus_one_utilities.
class SignatureFormTemplateFieldCollection extends EntityCollection<SignatureFormTemplateField> {
  SignatureFormTemplateFieldCollection() : super();

  factory SignatureFormTemplateFieldCollection.fromJson(List<dynamic> json) {
    return EntityCollection.fromJson(
      json: json,
      instance: SignatureFormTemplateFieldCollection(),
      entityFromJsonCallback: (x) => SignatureFormTemplateField.fromJson(x),
    );
  }
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class SignatureFormTemplateField extends Entity {
  SignatureFormTemplateField();

  /// A necessary factory constructor for creating a new SignatureFormTemplateField instance
  /// from a map. Pass the map to the generated [_$SignatureFormTemplateFieldFromJson()] constructor.
  /// The constructor is named after the source class, in this case, SignatureFormTemplateField.
  factory SignatureFormTemplateField.fromJson(Map<String, dynamic> json) =>
      _$SignatureFormTemplateFieldFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'Type')
  String? type;

  @JsonKey(name: 'PageIndex')
  int? pageIndex;

  @JsonKey(name: 'DocumentSignatureSessionRecipientID')
  String? documentSignatureSessionRecipientID;

  @JsonKey(name: 'X')
  double? x;

  @JsonKey(name: 'Y')
  double? y;

  @JsonKey(name: 'Label')
  String? label;

  @JsonKey(name: 'WidthPercent')
  double? widthPercent;

  @JsonKey(name: 'SortRank')
  int? sortRank;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$SignatureFormTemplateFieldToJson].
  @override
  Map<String, dynamic> toJson() => _$SignatureFormTemplateFieldToJson(this);
  // coverage:ignore-end
}
