import 'package:json_annotation/json_annotation.dart';

part 'subscription_details.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class SubscriptionDetails {
  SubscriptionDetails();

  /// A necessary factory constructor for creating a new SubscriptionDetails instance
  /// from a map. Pass the map to the generated [_$SubscriptionDetailsFromJson()] constructor.
  /// The constructor is named after the source class, in this case, SubscriptionDetails.
  factory SubscriptionDetails.fromJson(Map<String, dynamic> json) =>
      _$SubscriptionDetailsFromJson(json);

  @JsonKey(name: 'PaymentSubscriptionExists')
  bool? paymentSubscriptionExists;

  @JsonKey(name: 'PaymentPlanId')
  String? paymentPlanId;

  @JsonKey(name: 'TokenId')
  String? tokenId;

  @JsonKey(name: 'CustomerName')
  String? customerName;

  @JsonKey(name: 'BillingEmail')
  String? billingEmail;

  @JsonKey(name: 'PostalCode')
  String? postalCode;

  @JsonKey(name: 'OrganizationName')
  String? organizationName;

  @JsonKey(name: 'Expiration')
  String? expiration;

  @JsonKey(name: 'IsExpiringSoon')
  bool? isExpiringSoon;

  @JsonKey(name: 'FreeUsers')
  int? freeUsers;

  @JsonKey(name: 'IsExpired')
  bool? isExpired;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$SubscriptionDetailsToJson].
  Map<String, dynamic> toJson() => _$SubscriptionDetailsToJson(this);
  // coverage:ignore-end
}
