import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';
import 'query_result.dart';
part 'support_organization_tenant.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class SupportOrganizationTenantCollection implements IQueryResultEntityCollection {
  SupportOrganizationTenantCollection();

  /// A necessary factory constructor for creating a new FieldCollection instance
  /// from a map. Pass the map to the generated [_$SupportOrganizationTenantCollectionFromJson()] constructor.
  /// The constructor is named after the source class, in this case, FieldCollection.
  factory SupportOrganizationTenantCollection.fromJson(Map<String, dynamic> json) =>
      _$SupportOrganizationTenantCollectionFromJson(json);

  @JsonKey(name: 'Tenants')
  List<SupportOrganizationTenant>? supportOrganizationTenants;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$SupportOrganizationTenantCollectionToJson].
  Map<String, dynamic> toJson() => _$SupportOrganizationTenantCollectionToJson(this);
  // coverage:ignore-end
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class SupportOrganizationTenant extends Entity {
  SupportOrganizationTenant();

  /// A necessary factory constructor for creating a new SupportOrganizationTenant instance
  /// from a map. Pass the map to the generated [_$SupportOrganizationTenantFromJson()] constructor.
  /// The constructor is named after the source class, in this case, Tenant.
  factory SupportOrganizationTenant.fromJson(Map<String, dynamic> json) =>
      _$SupportOrganizationTenantFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'Name')
  String? name;

  @JsonKey(name: 'CreatingUserName')
  String? creatingUserName;

  @JsonKey(name: 'CreatingUserEmail')
  String? creatingUserEmail;

  @JsonKey(name: 'CrmAccountId')
  String? crmAccountId;

  @JsonKey(name: 'OrganizationID')
  String? organizationID;

  @JsonKey(name: 'OrganizationName')
  String? organizationName;

  @JsonKey(name: 'OrganizationSubscriptionRequired')
  bool? organizationSubscriptionRequired;

  @JsonKey(name: 'OrganizationSubscriptionExpiration')
  String? organizationSubscriptionExpiration;

  @JsonKey(name: 'SearchIndexID')
  String? searchIndexID;

  @JsonKey(name: 'BucketName')
  String? bucketName;

  @JsonKey(name: 'Disabled')
  bool? disabled;

  @JsonKey(name: 'IsMarkedForPurge')
  bool? isMarkedForPurge;

  @JsonKey(name: 'PurgeDate')
  String? purgeDate;

  @JsonKey(name: 'DocumentCount')
  int? documentCount;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$SupportOrganizationTenantToJson].
  Map<String, dynamic> toJson() => _$SupportOrganizationTenantToJson(this);
  // coverage:ignore-end
}
