import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';
import 'query_result.dart';
part 'support_organization.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class SupportOrganization extends Entity {
  SupportOrganization();

  /// A necessary factory constructor for creating a new SupportOrganization instance
  /// from a map. Pass the map to the generated [_$SupportOrganizationFromJson()] constructor.
  /// The constructor is named after the source class, in this case, Organization.
  factory SupportOrganization.fromJson(Map<String, dynamic> json) =>
      _$SupportOrganizationFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'Name')
  String? name;

  @JsonKey(name: 'CreatingUserName')
  String? creatingUserName;

  @JsonKey(name: 'CreatingUserEmail')
  String? creatingUserEmail;

  @JsonKey(name: 'SubscriptionRequired')
  bool? subscriptionRequired;

  @JsonKey(name: 'SubscriptionFreeUsers')
  int? subscriptionFreeUsers;

  @JsonKey(name: 'SubscriptionExpiration')
  String? subscriptionExpiration;

  @JsonKey(name: 'UniqueNonReadOnlyTenantMembers')
  int? uniqueNonReadOnlyTenantMembers;

  @JsonKey(name: 'UniqueReadOnlyTenantMembers')
  int? uniqueReadOnlyTenantMembers;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$SupportOrganizationToJson].
  @override
  Map<String, dynamic> toJson() => _$SupportOrganizationToJson(this);
  // coverage:ignore-end
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class SupportOrganizationCollection implements IQueryResultEntityCollection {
  SupportOrganizationCollection();

  /// A necessary factory constructor for creating a new SupportOrganizationCollection instance
  /// from a map. Pass the map to the generated [_$SupportOrganizationCollectionFromJson()] constructor.
  /// The constructor is named after the source class, in this case, SupportOrganizationCollection.
  factory SupportOrganizationCollection.fromJson(Map<String, dynamic> json) =>
      _$SupportOrganizationCollectionFromJson(json);

  @JsonKey(name: 'Organizations')
  List<SupportOrganization>? supportOrganizations;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$SupportOrganizationCollectionToJson].
  Map<String, dynamic> toJson() => _$SupportOrganizationCollectionToJson(this);
  // coverage:ignore-end
}
