import 'package:json_annotation/json_annotation.dart';

import 'query_result.dart';
import 'task_event.dart';

part 'task_comment.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class TaskCommentCollection implements IQueryResultEntityCollection {
  TaskCommentCollection();

  /// A necessary factory constructor for creating a new TaskCommentCollection instance
  /// from a map. Pass the map to the generated [_$TaskCommentsFromJson()] constructor.
  /// The constructor is named after the source class, in this case, TaskCommentCollection.
  factory TaskCommentCollection.fromJson(Map<String, dynamic> json) =>
      _$TaskCommentCollectionFromJson(json);

  @JsonKey(name: 'TaskEvents')
  List<TaskEvent>? taskEvents;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$TaskCommentsToJson].
  Map<String, dynamic> toJson() => _$TaskCommentCollectionToJson(this);
  // coverage:ignore-end

}
