import 'package:json_annotation/json_annotation.dart';
import '../common/api_model.dart';

part 'user_profile.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class UserProfile extends Entity {
  UserProfile();

  /// A necessary factory constructor for creating a new UserProfile instance
  /// from a map. Pass the map to the generated [_$UserProfileFromJson()] constructor.
  /// The constructor is named after the source class, in this case, UserProfile.
  factory UserProfile.fromJson(Map<String, dynamic> json) => _$UserProfileFromJson(json);

  @JsonKey(name: 'UserProvider')
  String? userProvider;

  @JsonKey(name: 'UserEmail')
  String? userEmail;

  @JsonKey(name: 'UserName')
  String? userName;

  @JsonKey(name: 'OTPSMSNumber')
  String? otpsmsNumber;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$UserProfileToJson].
  @override
  Map<String, dynamic> toJson() => _$UserProfileToJson(this);
  // coverage:ignore-end
}
