import 'package:json_annotation/json_annotation.dart';

import 'work_task_event.dart';

part 'work_task_comment.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class WorkTaskCommentCollection {
  WorkTaskCommentCollection();

  /// A necessary factory constructor for creating a new WorkTaskCommentCollection instance
  /// from a map. Pass the map to the generated [_$WorkTaskCommentsFromJson()] constructor.
  /// The constructor is named after the source class, in this case, WorkTaskCommentCollection.
  factory WorkTaskCommentCollection.fromJson(Map<String, dynamic> json) =>
      _$WorkTaskCommentCollectionFromJson(json);

  @JsonKey(name: 'WorkTaskEvents')
  List<WorkTaskEvent>? workTaskEvents;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$WorkTaskCommentsToJson].
  Map<String, dynamic> toJson() => _$WorkTaskCommentCollectionToJson(this);
  // coverage:ignore-end

}
