import 'package:json_annotation/json_annotation.dart';
import '../api_model/document.dart';
import '../common/api_model.dart';
import 'query_result.dart';

part 'work_task.g.dart';

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class WorkTaskCollection implements IQueryResultEntityCollection {
  WorkTaskCollection();

  /// A necessary factory constructor for creating a new FieldCollection instance
  /// from a map. Pass the map to the generated [_$WorkTaskCollectionFromJson()] constructor.
  /// The constructor is named after the source class, in this case, FieldCollection.
  factory WorkTaskCollection.fromJson(Map<String, dynamic> json) =>
      _$WorkTaskCollectionFromJson(json);

  @JsonKey(name: 'WorkTasks')
  List<WorkTask>? workTasks;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$WorkTaskCollectionToJson].
  Map<String, dynamic> toJson() => _$WorkTaskCollectionToJson(this);
  // coverage:ignore-end
}

// Originally generated by nucleus_one_utilities.
// Serializable members must be explicitly marked with [JsonKey].
@JsonSerializable(ignoreUnannotated: true, includeIfNull: false)
class WorkTask extends Entity {
  WorkTask();

  /// A necessary factory constructor for creating a new WorkTask instance
  /// from a map. Pass the map to the generated [_$WorkTaskFromJson()] constructor.
  /// The constructor is named after the source class, in this case, WorkTask.
  factory WorkTask.fromJson(Map<String, dynamic> json) => _$WorkTaskFromJson(json);

  @JsonKey(name: 'ID')
  String? id;

  @JsonKey(name: 'CreatedOn')
  String? createdOn;

  @JsonKey(name: 'ModifiedOn')
  String? modifiedOn;

  @JsonKey(name: 'CreatedByUserID')
  String? createdByUserID;

  @JsonKey(name: 'CreatedByUserEmail')
  String? createdByUserEmail;

  @JsonKey(name: 'CreatedByUserName')
  String? createdByUserName;

  @JsonKey(name: 'CompletedOn')
  String? completedOn;

  @JsonKey(name: 'CompletedByUserID')
  String? completedByUserID;

  @JsonKey(name: 'CompletedByUserEmail')
  String? completedByUserEmail;

  @JsonKey(name: 'CompletedByUserName')
  String? completedByUserName;

  @JsonKey(name: 'ModifiedByUserID')
  String? modifiedByUserID;

  @JsonKey(name: 'ModifiedByUserEmail')
  String? modifiedByUserEmail;

  @JsonKey(name: 'ModifiedByUserName')
  String? modifiedByUserName;

  @JsonKey(name: 'Revision')
  int? revision;

  @JsonKey(name: 'Result')
  String? result;

  @JsonKey(name: 'Name')
  String? name;

  @JsonKey(name: 'NameLower')
  String? nameLower;

  @JsonKey(name: 'Description')
  String? description;

  @JsonKey(name: 'DescriptionHtml')
  String? descriptionHtml;

  @JsonKey(name: 'DescriptionRichTextJson')
  String? descriptionRichTextJson;

  @JsonKey(name: 'RoleID')
  String? roleID;

  @JsonKey(name: 'RoleName')
  String? roleName;

  @JsonKey(name: 'RoleNameLower')
  String? roleNameLower;

  @JsonKey(name: 'DueOn')
  String? dueOn;

  @JsonKey(name: 'DueOnModifiedOn')
  String? dueOnModifiedOn;

  @JsonKey(name: 'PrimaryDocument')
  Document? primaryDocument;

  @JsonKey(name: 'OtherDocuments')
  List<Document>? otherDocuments;

  @JsonKey(name: 'ParentWorkTaskID')
  String? parentWorkTaskID;

  @JsonKey(name: 'ProcessID')
  String? processID;

  @JsonKey(name: 'ProcessName')
  String? processName;

  @JsonKey(name: 'ProcessNameLower')
  String? processNameLower;

  @JsonKey(name: 'ProcessElementID')
  String? processElementID;

  @JsonKey(name: 'ProcessElementName')
  String? processElementName;

  @JsonKey(name: 'ProcessElementNameLower')
  String? processElementNameLower;

  @JsonKey(name: 'Reminder_7_Day')
  String? reminder_7_Day;

  @JsonKey(name: 'Reminder_3_Day')
  String? reminder_3_Day;

  @JsonKey(name: 'Reminder_1_Day')
  String? reminder_1_Day;

  // coverage:ignore-start
  /// [toJson] is the convention for a class to declare support for serialization
  /// to JSON. The implementation simply calls the private, generated
  /// helper method [_$WorkTaskToJson].
  @override
  Map<String, dynamic> toJson() => _$WorkTaskToJson(this);
  // coverage:ignore-end
}
